#!/bin/bash

# Script: ops 301 class 05 ops Challenge
# Author: Osaremeh Abel
# Date of latest revision: 05/05/23
# Purpose: Write a bash script that clears a log file.
# Print to the screen the file size of the log files before compression
# Compress the contents of the log files to a backup directory
# File name should contain time stamp with the following format -YYYYMMDDHHMMSS
# Clear the contents of the log file
# Print to screen the file size of the compressed file
# Compare the size of the compressed files to the size of the original log files


#Main

#!/bin/bash

# Create log file
touch "star-wars.txt"

# Place text into new file
echo "Lorem Ipsum for Hackers generated by ChatGPT.
In a galaxy far, far away, a lone bounty hunter roams the lawless outer reaches of space.
Armed with his blaster, beskar armor, and unwavering determination, he takes on dangerous missions and battles against ruthless foes.
His name is Din Djarin, but to those who fear him, he is simply known as The Mandalorian." >> star-wars.txt


# Create a back-up directory
mkdir $starwars_backup

# view contents inside of .txt
cat star-wars.txt

# Define file to compress
LOG_FILES="star-wars.txt"

 # Define back up dir
BACKUP_DIR="starwars_backup"

# Define format for time stamp
TIMESTAMP=$(date +"s%m%d%Y")

# getting file size befor compression
 filesize=$(wc -c $LOG_FILES | awk '{print $1}')

echo "System log are currently $filesize bytes"

# zip the file to the backup directory with the timestamp

  zip -r "$BACKUP_DIR/$FILE_NAME-$TIMESTAMP.zip" "$LOG_FILES"

 # print out a confirmation that file is being zipped
echo "Compressing $BACKUP_DIR/$FILE_NAME-$TIMESTAMP.zip"

 # get the file size after compression
COMPRESSED_FILE_SIZE=$(wc -c "$BACKUP_DIR/$FILE_NAME-$TIMESTAMP.zip" | awk '{print $1}')

# clear the contents of the log file
  cat /dev/null > "$LOG_FILES"

 # print the file size before and after compression
  echo "File size before compression: $filesize"
  


