#!/bin/bash

# Script: ops 201 class 13 ops Challenge
# Author: Osaremeh Abel
# Date of latest revision: 03/27/23
# Purpose: Install whois on your Ubuntu VM
# Take a user input string. Presumably the string is a domain name such as Google.com.
# Run whois against a user input string 
# Run dig against the user input string.
# Run host against the user input string.
# Run nslookup against the user input string.

rocks="domain_name"

# Main

function mainman {
    echo "Enter a Domain name:"
    read rocks
    echo "=== Information about $rocks ==="
    
    whois $rocks >> results.txt
    
    echo "DIG Information:"
    dig $rocks >> results.txt
    
    echo "HOST Information:"
    host $rocks >> results.txt
    
    echo "NSLOOKUP Information:"
    nslookup $rocks >> results.txt

}

mainman
    






